### ISSUE TITLE
hyphen at "My Portfolio"

### ISSUE THREAD

**Issue by schmelto** [Yaseen549/Yaseen549#1]
![image](https://user-images.githubusercontent.com/30869493/116786031-05deb180-aa9d-11eb-96b2-f0d7736acb1c.png)

think this hyphen there was not intended. May you should remove it :)

**Comment by Yaseen549** [comment]
> ![image](https://user-images.githubusercontent.com/30869493/116786031-05deb180-aa9d-11eb-96b2-f0d7736acb1c.png)
> 
> think this hyphen there was not intended. May you should remove it :)

Thanks. I removed it.
